# Generated by Django 5.1.4 on 2024-12-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descriptiono',
            new_name='description',
        ),
    ]
